import { QueryRequest, Verdict } from '../orchestrator';

/**
 * Agent-γ (Gamma) — Deterministic rule engine (local, zero API cost)
 * Runs heuristic checks against address patterns, known exploit signatures,
 * and contract metadata. Instant, deterministic, reproducible.
 */

// Known addresses and their verdicts (real tokens)
const KNOWN_TOKENS: Record<string, { verdict: 'SAFE' | 'RISKY' | 'SCAM'; note: string }> = {
  '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48': { verdict: 'SAFE', note: 'USDC — Circle-issued stablecoin, audited, billions in circulation' },
  '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2': { verdict: 'SAFE', note: 'WETH — canonical wrapped Ether, widely trusted' },
  '0xdac17f958d2ee523a2206206994597c13d831ec7': { verdict: 'SAFE', note: 'USDT — Tether, largest stablecoin by volume' },
  '0x87230146e138d3f296a9d162a2dd8098f322b125': { verdict: 'RISKY', note: 'SQUID token — proxy with centralized ownership, transfer restrictions possible' },
  // Arc-native USDC
  '0x07865c6e87b9a5e213ae308ba4f8a9aadf7e2b0c': { verdict: 'SAFE', note: 'Arc USDC — official Circle USDC on Arc testnet' },
  // Argus own contracts
  '0x563b2da572948c2b54b5f1f26ccfebc153cb46c8': { verdict: 'SAFE', note: 'ArgusOracle — immutable verdict log, deployed by Argus team' },
  '0x0699a029e2e05ec88d6418ec744232702cf77d81': { verdict: 'SAFE', note: 'Argus Treasury — public treasury wallet, deployed by Argus team' },
  '0x4dd5e289168ddb28f9b34134eabccaf373eb64cb': { verdict: 'SAFE', note: 'Argus Funding Wallet — user onboarding faucet' },
  // Argus agent SCAs
  '0x284e38e6f139b3b85c746e00f8a3cf46d2b2d320': { verdict: 'SAFE', note: 'Agent Alpha — Circle-managed SCA wallet' },
  '0x3f752a72d8e2d9d3a4f2011ca9e0407bc5b7a34f': { verdict: 'SAFE', note: 'Agent Beta — Circle-managed SCA wallet' },
  '0x1fa79f59abbada269de477b45ded38c75a6146de': { verdict: 'SAFE', note: 'Agent Gamma — Circle-managed SCA wallet' },
};

// Heuristic checks based on address patterns
function hexEntropy(s: string) {
  const freq: Record<string, number> = {};
  for (const ch of s) freq[ch] = (freq[ch] || 0) + 1;
  const len = s.length;
  let ent = 0;
  for (const k of Object.keys(freq)) {
    const p = freq[k] / len;
    ent -= p * Math.log2(p);
  }
  return ent; // bits per symbol
}

const ADDRESS_CHECKS = [
  {
    name: 'Zero-byte address suffix',
    test: (addr: string) => addr.endsWith('0000') || addr.endsWith('00000'),
    flag: 'Address ends in zero bytes — common in vanity/precomputed addresses',
    score: 18,
  },
  {
    name: 'Repeating hex pattern',
    test: (addr: string) => /(.)\1{5,}/.test(addr.slice(2)),
    flag: 'Repeating hex sequence detected — vanity or autogenerated address',
    score: 18,
  },
  {
    name: 'Low entropy prefix',
    test: (addr: string) => hexEntropy(addr.slice(2, 18)) < 3.2,
    flag: 'Low-entropy address prefix — may indicate a precomputed or generated address',
    score: 20,
  },
  {
    name: 'Numeric-heavy sequence',
    test: (addr: string) => /\d{6,}/.test(addr.slice(2)),
    flag: 'Long numeric sequence in address — often used by obfuscated or mass-deployed contracts',
    score: 16,
  },
  {
    name: 'High digit ratio',
    test: (addr: string) => {
      const nums = addr.slice(2, 20).split('').filter(c => '0123456789'.includes(c)).length;
      return nums > 12;
    },
    flag: 'Numeric-heavy address — unusual for human-chosen addresses',
    score: 12,
  },
];

export const gammaAgent = {
  name: 'Agent-γ',
  model: 'Rule Engine (local)',

  async analyze(req: QueryRequest): Promise<Verdict> {
    const addr = req.contractAddress.toLowerCase();
    const flags: string[] = [];
    let riskScore = 0;

    // Check 1: Known token database
    const known = KNOWN_TOKENS[addr];
    if (known) {
      return {
        agent: 'Agent-γ',
        verdict: known.verdict,
        confidence: 95,
        reasoning: `Recognized address: ${known.note}.`,
        stake: '50000',
      };
    }

    // Check 2: Address heuristic patterns
    for (const check of ADDRESS_CHECKS) {
      if (check.test(addr)) {
        flags.push(check.flag);
        riskScore += check.score;
      }
    }

    // Check 3: Contract age heuristic (if first nibble high, slightly higher risk)
    const firstNibble = parseInt(addr[2], 16);
    if (!Number.isNaN(firstNibble) && firstNibble >= 12) {
      flags.push('Upper hex-range first nibble — modest correlation with newer contracts');
      riskScore += 4;
    }

    // Check 4: Common scam deployer patterns
    const deployerPrefix = addr.slice(2, 8);
    const suspiciousPrefixes = ['dead00', 'c0ffee', 'badc0d', '5ca400', 'def100'];
    if (suspiciousPrefixes.some(p => deployerPrefix.startsWith(p))) {
      flags.push('Address prefix matches known scam deployer pattern — elevated caution required');
      riskScore += 35;
    }

    // Check 5: Checksum validity (mixed case = EIP-55 checksum present)
    const hasMixedCase = req.contractAddress !== req.contractAddress.toLowerCase() && req.contractAddress !== req.contractAddress.toUpperCase();
    if (!hasMixedCase && req.contractAddress.length === 42) {
      flags.push('Address not checksummed — cannot verify address integrity, potential typo-squatting risk');
      riskScore += 6;
    }

    // Determine verdict
    // Adjusted thresholds after aggregating refined heuristics
    let verdict: 'SAFE' | 'RISKY' | 'SCAM' = 'SAFE';
    if (riskScore >= 50) verdict = 'SCAM';
    else if (riskScore >= 20) verdict = 'RISKY';

    // Build reasoning
    let reasoning: string;
    if (flags.length === 0) {
      reasoning = 'Address passes all deterministic heuristic checks. No known scam signatures, no suspicious patterns detected in address structure, and no match in blacklist database. While this does not guarantee safety, the address shows no structural red flags.';
    } else if (flags.length <= 2) {
      reasoning = flags.join('. ') + '.';
    } else {
      reasoning = `Multiple risk indicators detected: ${flags.slice(0, 3).join('. ')}. ${flags.length > 3 ? `Plus ${flags.length - 3} additional flags.` : ''}`;
    }

    // Map riskScore to a calibrated confidence (higher risk -> lower confidence)
    let confidence: number;
    if (verdict === 'SAFE') {
      confidence = Math.min(95, 90 - Math.round(riskScore / 1.5));
      confidence = Math.max(55, confidence);
    } else if (verdict === 'RISKY') {
      confidence = Math.max(30, 70 - Math.round(riskScore / 1.2));
    } else {
      confidence = Math.max(10, 50 - Math.round((riskScore - 50) / 2));
    }

    return {
      agent: 'Agent-γ',
      verdict,
      confidence,
      reasoning,
      stake: '50000',
    };
  },
};
